// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLcVchONH6s06L24F6rUKeTQwufpGZD-M',
    appId: '1:497881747557:web:54f99e680d2da2afe0768c',
    messagingSenderId: '497881747557',
    projectId: 'db-5f982',
    authDomain: 'petappdb-5f982.firebaseapp.com',
    storageBucket: 'petappdb-5f982.appspot.com',
    measurementId: 'G-72HG29PMS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmbTDViDDRKkDgbL4bpsdtD4lRFSdcNCQ',
    appId: '1:497881747557:android:6e899edfc09e8319e0768c',
    messagingSenderId: '497881747557',
    projectId: 'petappdb-5f982',
    storageBucket: 'petappdb-5f982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWFlBI2C_mH7Tnrr3d6kN9KSsgdnTxwxA',
    appId: '1:497881747557:ios:97793349d17e07c1e0768c',
    messagingSenderId: '497881747557',
    projectId: 'petappdb-5f982',
    storageBucket: 'petappdb-5f982.appspot.com',
    iosBundleId: 'com.example.dismovApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWFlBI2C_mH7Tnrr3d6kN9KSsgdnTxwxA',
    appId: '1:497881747557:ios:3a5d72e1c8ae22a3e0768c',
    messagingSenderId: '497881747557',
    projectId: 'petappdb-5f982',
    storageBucket: 'petappdb-5f982.appspot.com',
    iosBundleId: 'com.example.dismovApp.RunnerTests',
  );
}
